### ISSUE TITLE
"npm start" fails

### ISSUE THREAD

**Issue by rikuson** [nthiebes/booky.io#14]
Hi, I love booky.io, and I'm wondering if I can contribute for this.  
So I cloned your project and tried to build.  
But I have faced error below.

```
$ npm install
$ npm start
...
2017-08-02 02:26 node[15085] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-08-02 02:26 node[15085] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-08-02 02:26 node[15085] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1282:11)
```

How can I start locally?

**Environment**  
node: v7.3.0  
npm: v3.10.10

**Comment by nthiebes** [comment]
Hi! Sorry for the late reply, didn't see the email. Thanks for your interest in contributing! :)

I already restructured a lot of the things you see in master. There is still a lot of base work to be done and I'm quite busy with other things right now. When I'm done with all this I can start creating issues etc. that can be worked on also by others. I'll keep you updated.
